### ISSUE TITLE
Help file

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/O21#19]
As a historical artifact, the game help file may be interesting, so why not add the ability to read it in the game itself?

Document any notes in the `docs/resources.md` file.

## TODO
- [x] Read the `U95.HLP` file (#43)
- [x] Learn to read the bitmaps from the file
- [ ] Render the help somewhere in the game

**Comment by ForNeVeR** [comment]
http://www.oocities.org/mwinterhoff/helpfile.htm

**Comment by ForNeVeR** [comment]
Some screenshots (I'm sorry for the broken encoding, hopefully we'll extract the exact contents from the game files anyway, so only layout is of interest here):
<img width="331" alt="image" src="https://user-images.githubusercontent.com/92793/226188472-ec330fde-b68d-4a51-80ff-9bcb4841d5ef.png">
<img width="323" alt="image" src="https://user-images.githubusercontent.com/92793/226188597-db6ea373-175b-4a61-9891-d6a09d9d338a.png">

It looks like the game only has one topic, dubbed "the untitled topic" (though this name is not used in the file).
<img width="173" alt="image" src="https://user-images.githubusercontent.com/92793/226188659-221b4bb5-c2cc-4181-8444-fb3a90ec72ba.png">
